package com.myspace.onboarding;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("first Name")
	private java.lang.String firstName;
	@org.kie.api.definition.type.Label("Last Name")
	private java.lang.String lastName;
	@org.kie.api.definition.type.Label("Domicile")
	private java.lang.String domicile;
	@org.kie.api.definition.type.Label("Minor")
	private java.lang.Boolean minor;
	@org.kie.api.definition.type.Label("Relation")
	private java.lang.String relation;

	@org.kie.api.definition.type.Label("id")
	private java.lang.String id;

	@org.kie.api.definition.type.Label("isNew")
	private java.lang.Boolean isNew;

	@org.kie.api.definition.type.Label("role")
	private java.lang.String role;

	@org.kie.api.definition.type.Label(value = "dateOfBirth")
	private java.lang.String dateOfBirth;

	public Person() {
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public java.lang.String getDomicile() {
		return this.domicile;
	}

	public void setDomicile(java.lang.String domicile) {
		this.domicile = domicile;
	}

	public java.lang.Boolean getMinor() {
		return this.minor;
	}

	public void setMinor(java.lang.Boolean minor) {
		this.minor = minor;
	}

	public java.lang.String getRelation() {
		return this.relation;
	}

	public void setRelation(java.lang.String relation) {
		this.relation = relation;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.Boolean getIsNew() {
		return this.isNew;
	}

	public void setIsNew(java.lang.Boolean isNew) {
		this.isNew = isNew;
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public java.lang.String getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(java.lang.String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public Person(java.lang.String firstName, java.lang.String lastName,
			java.lang.String domicile, java.lang.Boolean minor,
			java.lang.String relation, java.lang.String id,
			java.lang.Boolean isNew, java.lang.String role,
			java.lang.String dateOfBirth) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.domicile = domicile;
		this.minor = minor;
		this.relation = relation;
		this.id = id;
		this.isNew = isNew;
		this.role = role;
		this.dateOfBirth = dateOfBirth;
	}

}