package com.myspace.onboarding;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Account implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Type")
	private java.lang.String type;

	@org.kie.api.definition.type.Label("Currency")
	private java.lang.String currency;

	@org.kie.api.definition.type.Label("Jurisdiction")
	private java.lang.String jurisdiction;

	@org.kie.api.definition.type.Label("Sub Type")
	private java.lang.String subType;

	@org.kie.api.definition.type.Label("Access")
	private java.lang.String access;

	@org.kie.api.definition.type.Label("Description")
	private java.lang.String description;

	@org.kie.api.definition.type.Label(value = "name")
	private java.lang.String name;

	public Account() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getCurrency() {
		return this.currency;
	}

	public void setCurrency(java.lang.String currency) {
		this.currency = currency;
	}

	public java.lang.String getJurisdiction() {
		return this.jurisdiction;
	}

	public void setJurisdiction(java.lang.String jurisdiction) {
		this.jurisdiction = jurisdiction;
	}

	public java.lang.String getSubType() {
		return this.subType;
	}

	public void setSubType(java.lang.String subType) {
		this.subType = subType;
	}

	public java.lang.String getAccess() {
		return this.access;
	}

	public void setAccess(java.lang.String access) {
		this.access = access;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public Account(java.lang.String type, java.lang.String currency,
			java.lang.String jurisdiction, java.lang.String subType,
			java.lang.String access, java.lang.String description,
			java.lang.String name) {
		this.type = type;
		this.currency = currency;
		this.jurisdiction = jurisdiction;
		this.subType = subType;
		this.access = access;
		this.description = description;
		this.name = name;
	}

}